name: CI/CD

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine GHCR image tag (lowercase)
        id: image
        run: |
          # extract repo (owner/repo -> repo)
          repo_name="${GITHUB_REPOSITORY#*/}"
          # lowercase owner and repo (GHCR requires lowercase names)
          lower_owner="$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')"
          lower_repo="$(echo "${repo_name}" | tr '[:upper:]' '[:lower:]')"
          image="ghcr.io/${lower_owner}/${lower_repo}:latest"
          echo "image=${image}" >> $GITHUB_OUTPUT
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.image.outputs.image }}

  deploy-pages:
    needs: build-and-publish
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
