name: CI/CD

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine GHCR image tag (lowercase)
        id: image
        run: |
          # repo is owner/repo, extract owner and repo
          owner="${GITHUB_REPOSITORY%%/*}"
          repo_name="${GITHUB_REPOSITORY#*/}"
          # lowercase owner and repo (GHCR requires lowercase names)
          lower_owner="$(echo "${owner}" | tr '[:upper:]' '[:lower:]')"
          lower_repo="$(echo "${repo_name}" | tr '[:upper:]' '[:lower:]')"
          image="ghcr.io/${lower_owner}/${lower_repo}:latest"
          echo "image=${image}" >> $GITHUB_OUTPUT
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.image.outputs.image }}

  deploy-pages:
    needs: build-and-publish
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Pages token
        id: set_token
        run: |
          if [ -n "${GH_PAGES_PAT}" ]; then
            echo "token=${GH_PAGES_PAT}" >> $GITHUB_OUTPUT
          else
            echo "token=${GITHUB_TOKEN}" >> $GITHUB_OUTPUT
          fi
        env:
          GH_PAGES_PAT: ${{ secrets.GH_PAGES_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ steps.set_token.outputs.token }}
          publish_dir: ./docs
